---
version: '3'
services:
  web:
    build:
      context: .
    privileged: true
    command: bundle exec puma -C ./config/puma.rb -e production
    ports:
      - "1337:1337"
    volumes:
      - "./db:/app/db:z"
      - "./log:/app/log:z"
      - "./tmp:/app/tmp:z"
    links:
      - redis
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=sqlite3:/app/db/production.sqlite3

  sidekiq:
    build:
      context: .
    privileged: true
    cap_add:
      - "NET_RAW"
      - "NET_ADMIN"
      - "NET_BIND_SERVICE"
    command: bundle exec sidekiq -C ./config/sidekiq.yml -r ./config/sidekiq.rb -r ./workers.rb -e production
    volumes:
      - "./db:/app/db:z"
      - "./log:/app/log:z"
      - "./tmp:/app/tmp:z"
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=sqlite3:/app/db/production.sqlite3

  redis:
    image: redis
