---
version: '3'
services:
  web:
    build:
      context: .
    privileged: true
    command: bundle exec foreman start web
    ports:
      - "1337:1337"
    volumes:
      - "${HOME}/.config/ronin-db:/home/ronin/.config/ronin-db:z"
      - "${HOME}/.local/share/ronin-db:/home/ronin/.local/share/ronin-db:z"
      - "${HOME}/.cache/ronin:/home/ronin/.cache/ronin:z"
      - "${HOME}/.cache/ronin-repos:/home/ronin/.cache/ronin-repos:z"
      - "${HOME}/.cache/ronin-nmap:/home/ronin/.cache/ronin-nmap:z"
      - "${HOME}/.cache/ronin-masscan:/home/ronin/.cache/ronin-masscan:z"
      - "./log:/app/log:z"
      - "./tmp:/app/tmp:z"
    links:
      - redis
    environment:
      - PORT=1337
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  sidekiq:
    build:
      context: .
    privileged: true
    cap_add:
      - "NET_RAW"
      - "NET_ADMIN"
      - "NET_BIND_SERVICE"
    command: bundle exec foreman start sidekiq
    volumes:
      - "${HOME}/.config/ronin-db:/home/ronin/.config/ronin-db:z"
      - "${HOME}/.local/share/ronin-db:/home/ronin/.local/share/ronin-db:z"
      - "${HOME}/.cache/ronin:/home/ronin/.cache/ronin:z"
      - "${HOME}/.cache/ronin-repos:/home/ronin/.cache/ronin-repos:z"
      - "${HOME}/.cache/ronin-nmap:/home/ronin/.cache/ronin-nmap:z"
      - "${HOME}/.cache/ronin-masscan:/home/ronin/.cache/ronin-masscan:z"
      - "./log:/app/log:z"
      - "./tmp:/app/tmp:z"
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis
